-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.customers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  company text NOT NULL,
  email text,
  phone text,
  country text DEFAULT 'TH'::text,
  industry text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  last_reviewed_at date DEFAULT CURRENT_DATE,
  review_days integer DEFAULT 180,
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documents (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  product text NOT NULL,
  doc_type text NOT NULL,
  file_size text,
  tags ARRAY,
  file_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inquiries (
  id text NOT NULL,
  customer text NOT NULL,
  product text NOT NULL,
  spec text,
  supplier text,
  supplier_deadline date,
  status text DEFAULT 'pending'::text,
  can_make text DEFAULT '待確認'::text,
  lead_time text,
  moq text,
  raw_material text,
  supplier_price text,
  margin text DEFAULT '20'::text,
  remarks text,
  doc_sent boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  supplier_email text,
  last_contacted timestamp with time zone,
  supplier_cc ARRAY,
  from_product_id bigint,
  CONSTRAINT inquiries_pkey PRIMARY KEY (id),
  CONSTRAINT inquiries_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES public.products(id)
);
CREATE TABLE public.order_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  order_id text,
  spec text,
  unit text DEFAULT 'm²'::text,
  unit_price numeric,
  amount numeric,
  notes text,
  product_id bigint,
  product_name text,
  qty numeric,
  currency text DEFAULT 'USD'::text,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.orders (
  id text NOT NULL,
  customer text NOT NULL,
  status text DEFAULT 'confirmed'::text,
  total_amount numeric,
  currency text DEFAULT 'USD'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  quote_header_id text,
  customer_id bigint,
  supplier_id bigint,
  order_date date DEFAULT CURRENT_DATE,
  expected_delivery date,
  actual_delivery date,
  tracking_no text,
  updated_at timestamp with time zone DEFAULT now(),
  transport_method text,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.products (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  product_code text,
  product_name text NOT NULL,
  supplier_id bigint,
  unit text DEFAULT 'roll'::text,
  cost_price numeric,
  currency text DEFAULT 'JPY'::text,
  review_days integer DEFAULT 90,
  last_reviewed_at date DEFAULT CURRENT_DATE,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  min_stock_qty numeric DEFAULT 0,
  stock_qty numeric DEFAULT 0,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.purchase_order_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  po_id text,
  product_id bigint,
  product_name text NOT NULL,
  spec text,
  qty numeric,
  unit text,
  unit_price numeric,
  currency text DEFAULT 'USD'::text,
  amount numeric,
  notes text,
  rolls_qty numeric,
  width_m numeric,
  pricing_unit text,
  ref_order_id text,
  received_qty numeric,
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_po_id_fkey FOREIGN KEY (po_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.purchase_orders (
  id text NOT NULL,
  accounting_no text,
  source text DEFAULT 'order'::text,
  ref_order_id text,
  ref_sample_id bigint,
  supplier_id bigint,
  customer_note text,
  status text DEFAULT 'draft'::text,
  approval_status text DEFAULT 'none'::text,
  approved_by text,
  approved_at timestamp with time zone,
  order_date date DEFAULT CURRENT_DATE,
  expected_delivery date,
  actual_delivery date,
  currency text DEFAULT 'USD'::text,
  total_amount numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_ref_order_id_fkey FOREIGN KEY (ref_order_id) REFERENCES public.orders(id),
  CONSTRAINT purchase_orders_ref_sample_id_fkey FOREIGN KEY (ref_sample_id) REFERENCES public.samples(id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.quote_headers (
  id text NOT NULL,
  version integer DEFAULT 1,
  parent_id text,
  inquiry_id text,
  customer text NOT NULL,
  status text DEFAULT 'draft'::text,
  valid_until date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  source text,
  supplier text,
  CONSTRAINT quote_headers_pkey PRIMARY KEY (id),
  CONSTRAINT quote_headers_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.quote_headers(id),
  CONSTRAINT quote_headers_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id)
);
CREATE TABLE public.quote_items (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  quote_id text,
  inquiry_id text,
  product text NOT NULL,
  spec text,
  supplier text,
  cost_price numeric,
  cost_currency text DEFAULT 'USD'::text,
  customs_fee_pct numeric DEFAULT 7.5,
  apply_customs boolean DEFAULT true,
  margin_pct numeric DEFAULT 20,
  quoted_price numeric,
  unit text DEFAULT 'm²'::text,
  notes text,
  header_id text,
  moq text,
  lead_time text,
  product_id integer,
  supplier_id integer,
  CONSTRAINT quote_items_pkey PRIMARY KEY (id),
  CONSTRAINT quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quote_headers(id),
  CONSTRAINT quote_items_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id),
  CONSTRAINT quote_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT quote_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.quotes (
  id text NOT NULL,
  inquiry_id text,
  customer text NOT NULL,
  product text NOT NULL,
  spec text,
  supplier text,
  cost_price text,
  cost_currency text DEFAULT 'USD'::text,
  customs_fee_pct numeric DEFAULT 7.5,
  apply_customs boolean DEFAULT true,
  margin_pct numeric DEFAULT 20,
  quoted_price text,
  quoted_currency text DEFAULT 'USD'::text,
  status text DEFAULT 'pending'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id)
);
CREATE TABLE public.sample_requests_in (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  sample_id bigint,
  supplier_id bigint,
  requested_date date DEFAULT CURRENT_DATE,
  received_date date,
  qty numeric,
  cost numeric,
  cost_currency text DEFAULT 'USD'::text,
  status text DEFAULT 'pending'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sample_requests_in_pkey PRIMARY KEY (id),
  CONSTRAINT sample_requests_in_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id),
  CONSTRAINT sample_requests_in_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.sample_shipments_out (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  sample_id bigint,
  customer_id bigint,
  shipped_date date DEFAULT CURRENT_DATE,
  tracking_no text,
  qty numeric,
  status text DEFAULT 'shipped'::text,
  feedback text,
  feedback_date date,
  create_quote boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sample_shipments_out_pkey PRIMARY KEY (id),
  CONSTRAINT sample_shipments_out_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id),
  CONSTRAINT sample_shipments_out_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.samples (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  product_name text NOT NULL,
  spec text,
  supplier_id bigint,
  from_inquiry_id text,
  from_product_id bigint,
  stock_qty numeric DEFAULT 0,
  unit text,
  notes text,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT samples_pkey PRIMARY KEY (id),
  CONSTRAINT samples_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT samples_from_inquiry_id_fkey FOREIGN KEY (from_inquiry_id) REFERENCES public.inquiries(id),
  CONSTRAINT samples_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES public.products(id)
);
CREATE TABLE public.settings (
  key text NOT NULL,
  value text NOT NULL,
  label text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.supplier_group_members (
  group_id bigint NOT NULL,
  supplier_id bigint NOT NULL,
  role text DEFAULT 'cc'::text,
  CONSTRAINT supplier_group_members_pkey PRIMARY KEY (group_id, supplier_id),
  CONSTRAINT supplier_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.supplier_groups(id),
  CONSTRAINT supplier_group_members_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.supplier_groups (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT supplier_groups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.suppliers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  company text,
  email text NOT NULL,
  phone text,
  line_id text,
  whatsapp text,
  specialty text,
  created_at timestamp with time zone DEFAULT now(),
  salutation text,
  role text,
  line_group_id text,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tasks (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  title text NOT NULL,
  source text DEFAULT 'manual'::text,
  ref_module text,
  ref_id text,
  supplier_id bigint,
  customer_id bigint,
  due_date date,
  priority text DEFAULT 'normal'::text,
  status text DEFAULT 'open'::text,
  notes text,
  auto_generated boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT tasks_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.users (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  email text NOT NULL UNIQUE,
  name text,
  role text DEFAULT 'assistant'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  password_hash text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
